trigger:
  - master

pool:
  name: Default

steps:
  # Build + Test
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      goals: 'clean install'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'

  # Publish JAR artifact
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'target'
      ArtifactName: 'springboot-app'


  - script: |
      docker build -t $(dockerHubUsername)/$(imageName):latest .
    displayName: 'Build Docker Image'

  - script: |
      echo $(dockerPassword) | docker login -u $(dockerHubUsername) --password-stdin
    displayName: 'Docker Login'

  - script: |
      docker push $(dockerHubUsername)/$(imageName):latest
    displayName: 'Push Docker Image'

