trigger:
  - master

pool:
  name: Default

steps:

  - task: MavenAuthenticate@0
    inputs:
      artifactsFeeds: 'newFeed'

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      goals: 'clean deploy'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'target'
      ArtifactName: 'springboot-app'

  - script: |
      docker build -t $(dockerHubUsername)/$(imageName):$(Build.BuildId) .
    displayName: 'Build Docker Image'

  - script: |
      echo $(dockerPassword) | docker login -u $(dockerHubUsername) --password-stdin
    displayName: 'Docker Login'

  - script: |
      docker push $(dockerHubUsername)/$(imageName):$(Build.BuildId)
    displayName: 'Push Docker Image'